### ISSUE TITLE
Steam discrepancy

### ISSUE THREAD

**Issue by Staegrin** [bdew-minecraft/generators#21] opened 2015-02-07 13:36 UTC
So I set up a maximum size heat exchanger next to a maximum size steam turbine generator.

The heat exchanger creates 3,962 mB/T of steam when I use a pressurized output/input valve next to each other to transfer the steam from one to the other 1,962mB/T of steam disappears from the system. The internal buffer in the exchanger doesn't climb and the steam turbine generator only consumes 2,000 mB/T. 

![2015-02-07_14 27 46](https://cloud.githubusercontent.com/assets/8494635/6092228/a6c6249a-aed5-11e4-8c60-8550d60bfc77.png)
If the steam is first output to a drum on the other hand and then the steam gets transferred to the steam turbine the drum will fill up with the excess steam.

![2015-02-07_14 37 57](https://cloud.githubusercontent.com/assets/8494635/6092255/f68bbe8a-aed6-11e4-89f2-555aa0de673d.png)
Exchanger says it is only outputting 2,000 mB so where does the rest go?

**Comment by bdew** [comment] 2015-02-07 15:38
That's odd. I've experimented a bit and couldn't reproduce it.

Are you sure it doesn't end up going elsewhere? If there are other things connected to the same pressure input, they will be in the same "pressure network". 

You can spawn a Pressure system debugger item and shift+rightclick the output, then look at the line that says "Outs:" for a list of block coordinates it can output to.

**Comment by bdew** [comment] 2015-02-07 15:43
Wait nevermind, i was looking at your old screenshot that showed 3962 output.

Is it actually outputs only 2000 and produces 3962 and it doesn't fill the buffer? That's really weird.

Can you post screensots of your setup including how everything is connected and all guis?

**Comment by Staegrin** [comment] 2015-02-07 23:58
So first for the set-up with the drum
![2015-02-08_00 49 06](https://cloud.githubusercontent.com/assets/8494635/6094497/77d9a90c-af2c-11e4-83ab-78687b0c9031.png)
Drum fills up with excess steam. 2,000 mB/T steam gets pulled out by high pressure input. Fluid output valve dumps 3,962 mB/T into the drum.

![2015-02-08_00 48 49](https://cloud.githubusercontent.com/assets/8494635/6094498/79ca57b6-af2c-11e4-83c8-4059b55b3c3f.png)
Red output is diamond chest for the obsidian.

![2015-02-08_00 48 34](https://cloud.githubusercontent.com/assets/8494635/6094499/7b8cdba0-af2c-11e4-9db9-dbbc2cbd976d.png)

![2015-02-08_00 48 21](https://cloud.githubusercontent.com/assets/8494635/6094500/7d1a78b0-af2c-11e4-8433-d71375207c92.png)

![2015-02-08_00 55 25](https://cloud.githubusercontent.com/assets/8494635/6094516/3cc4c620-af2d-11e4-9e99-dbd8a872345e.png)

![2015-02-08_00 55 30](https://cloud.githubusercontent.com/assets/8494635/6094518/4119b1d6-af2d-11e4-81f0-da156692160b.png)

**Comment by Staegrin** [comment] 2015-02-08 00:11
Now the set-up with the pressure output and input

![2015-02-08_00 59 38](https://cloud.githubusercontent.com/assets/8494635/6094525/f258e7c8-af2d-11e4-8699-866eb771fcff.png)
Because the two multiblock structures are 2 blocks apart we can reposition the pressurized input valve and replace the fluid output valve with a pressurized output valve. Thereby not needing the pressure pipes or the drum.

![2015-02-08_01 00 17](https://cloud.githubusercontent.com/assets/8494635/6094526/f3dd0304-af2d-11e4-9e46-665ad6ee8db3.png)

![2015-02-08_01 00 18](https://cloud.githubusercontent.com/assets/8494635/6094527/f5abcbc0-af2d-11e4-8a67-2ae2fd684252.png)

![2015-02-08_00 59 55](https://cloud.githubusercontent.com/assets/8494635/6094530/08f66172-af2e-11e4-952b-019dcec8b456.png)
The output configuration says it is outputting 2,000 mB/T of steam.
![2015-02-08_01 00 07](https://cloud.githubusercontent.com/assets/8494635/6094531/0a29c4da-af2e-11e4-9fdd-89c1ee05fdf5.png)

The internal 16 bucket reservoir keeps saying only 3,962 Buckets are stored.
![2015-02-08_01 09 03](https://cloud.githubusercontent.com/assets/8494635/6094551/1b99e8e8-af2f-11e4-8602-4f04fb6eb9e8.png)

And if we add the fluid output valve back on it should be dumping 1,962 mB/T of steam into the drum but isn't.

PS: my drum just filled up. It can now only accept 2,000 mB/T as that's what is getting pumped out for the steam turbine. The output from the heat exchanger has dropped to 2,000 mB and the internal storage still hasn't risen above 3,962

**Comment by bdew** [comment] 2015-02-08 22:23
Try this versions (you need to update both):

http://jenkins.bdew.net/job/bdlib-1.7.10/41/artifact/build/libs/bdlib-mc1710-1.6.2.41.jar
http://jenkins.bdew.net/job/generators-1.7.10/36/artifact/build/libs/generators-mc1710-0.9.8.36.jar

**Comment by Staegrin** [comment] 2015-02-09 15:10
It seems to be fixed. Steam is no longer disappearing from the system. The internal buffer fills up when it should.

**Closed as completed** 2015-02-09 15:12 UTC
