### ISSUE TITLE
Gas Turbine banks lose syngas when unloaded

### ISSUE THREAD

**Issue by RogueShadow** [bdew-minecraft/generators#95] opened 2016-05-15 11:34 UTC
I've been losing all the syngas I put in the gas turbine's tank when the area is unloaded and reloaded.
The generator is connected directly to the output of the syngas generator, i've been feeding by hand because neotech pipe issue, and no pumps in the pack. outputting power with the neotech energy cube thing and pipes. Is anybody else having this issue, I didn't notice it, now I wanna test further.

**Comment by bdew** [comment] 2016-05-16 08:20
Is this in 1.9?

**Comment by RogueShadow** [comment] 2016-05-16 12:44
Yes, sorry.

**Comment by bdew** [comment] 2016-05-19 13:31
Sorry for the delay, i've tried and i can't reproduce this.

What exact versions are you using of all mods involved? (including bdlib and forge)
Anything special about the setup?

**Comment by RogueShadow** [comment] 2016-05-20 14:50
https://www.dropbox.com/s/i9f6b8vuky8b8y7/mods.txt?dl=0
Forge-12.16.1.1904
Here are all the mods we are using now. I just made a video showing how it's setup, and how it vanishes when it's unloaded. "queued for processing" https://youtu.be/KpAc82xbZWA

**Comment by DiscipleOfUrza** [comment] 2016-09-01 04:31
I too have this happen. It will happen to me with any fuel. Ethanol, Fire Water, Rocket Fuel, Refined Oil...if I save and quit, or not have a chunkloader and move too far away, the internal fuel buffers will clear themselves out.

**Comment by DiscipleOfUrza** [comment] 2016-09-12 04:59
In regard to my last comment, I have found that the only way to prevent this from happening is to use a tank from your Pressure Pipes mod immediately before connecting to the generator.

**Comment by bdew** [comment] 2016-09-13 16:21
>  the only way to prevent this from happening is to use a tank from your Pressure Pipes mod immediately before connecting to the generator

So if you put any pipes between the tank and the generator does it start happening again? What kind of pipes are you using?

**Comment by DiscipleOfUrza** [comment] 2016-09-26 04:26
I've always used EnderIO Conduits.  Regardless of the tier of pipes, they still produce the same result. It's more that the internal buffer of the generator clear itself out. I've updated everything again, including Forge; will test a few times tomorrow.

**Comment by TheOldOne822** [comment] 2017-01-16 20:54
I'm seeing internal fuel buffer on the Gas Turbine clear when an area is unloaded as well. 
Versions
Minecraft 1.10.2
forge 12.18.3.2185
generators 0.9.20.19
bdlib 1.12.2.20

**Comment by bdew** [comment] 2017-10-12 16:47
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.

**Closed as completed by bdew** 2017-10-12 16:47 UTC

**Comment by DiscipleOfUrza** [comment] 2017-10-13 02:37
I appreciate the feedback. I admit this is something that fell on my
backburner as I mover on to other games. I plan on updating to 1.12 upon
finishing my new computer, but I really do appreciate a mod maker who
follows up on. Such an old problem. Rest assured advanced generators will
be in my new personal modpack :)
