### ISSUE TITLE
[1.8.9] Fatally Missing Blocks or Items

### ISSUE THREAD

**Issue by kreezxil** [bdew-minecraft/generators#88] opened 2016-04-20 19:15 UTC
I'm not sure which one of your 1.8.9 mods did it, because there is no error log generated, just a mysterious statement about 2 missing blocks and 2 items.

I disabled a bunch of mods in pack and the issue didn't resolve until I disabled all three of yours.

BDLIB
PRESSURE PIPES
ADVANCED GENERATORS

These are for the updates you created on the 18th.

The problem doesn't reveal itself if you play in SSP. It is only noticeable when you do SMP. 

Once again, no crash occurs, therefore no crash log, the server doesn't say which mod generated it, the client says that line tho, but it also doesn't say what mod created it.

Other than all of this, great work and keep at it!

**Comment by bdew** [comment] 2016-04-21 07:10
I can't reproduce this with a server.

Make sure all your configs are the same between the server and the client, and all mods (and forge) are on the same version.

If it still happens please upload the full logs from both client and server.

**Comment by bdew** [comment] 2017-10-12 16:46
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.

**Closed as completed by bdew** 2017-10-12 16:46 UTC
