### ISSUE TITLE
Fluid Output not working with NeoTech fluid pipes

### ISSUE THREAD

**Issue by JCMais** [bdew-minecraft/generators#91] opened 2016-04-21 21:00 UTC
Minecraft version: 1.9.2
Forge Version: 1863
Advanced Generators: 9.20.7
NeoTech version: 1.9-3.0.5

I don't know if I should be reporting this here or in the NeoTech project.

![2016-04-21_17 54 39](https://cloud.githubusercontent.com/assets/1041647/14724017/3097057c-07ea-11e6-8234-fca871155046.png)

This is a strange issue, right now, only the input ports are receiving liquids coming from NeoTech pipes (it's getting the water from the Creative Tank), but the Fluid Output Port cannot send the liquid (syngas in this case) to the tank using the pipe.

![2016-04-21_17 57 39](https://cloud.githubusercontent.com/assets/1041647/14724111/9ec18a18-07ea-11e6-97c2-58dbb78f8f44.png)

The same issue is affecting Pressure Pipes, so I don't know if this is an issue directly with bdlib. 

![2016-04-21_17 59 57](https://cloud.githubusercontent.com/assets/1041647/14724189/f583b5a6-07ea-11e6-8492-46e1c963a6ae.png)

**Comment by bdew** [comment] 2016-04-22 13:06
The problem is that my multiblocks can currently only push fluids and NT pipes can only pull them. I have a planned workaround, but haven't gotten around to implementing it yet. You can use some other kind of tank as a buffer for now.

**Comment by bdew** [comment] 2017-10-12 16:46
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.

**Closed as completed by bdew** 2017-10-12 16:46 UTC
